[versions]
kotlin = "1.9.22"
compose = "1.5.4"
room = "2.6.1"
agp = "8.1.0"  # Android Gradle Plugin 版本

[libraries]
# Core
androidx-core = { module = "androidx.core:core-ktx", version = "1.12.0" }
androidx-lifecycle = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version = "2.7.0" }

# Compose
compose-bom = { module = "androidx.compose:compose-bom", version = "2023.10.01" }
compose-ui.module = "androidx.compose.ui:ui"
compose-material3.module = "androidx.compose.material3:material3"

# Database
room-runtime = { module = "androidx.room:room-runtime", version.ref = "room" }
room-ktx = { module = "androidx.room:room-ktx", version.ref = "room" }

# Chart
mpandroidchart = "com.github.PhilJay:MPAndroidChart:v3.1.0"

# 添加插件部分
[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }